"use client";

import { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

export default function RashEngineButton({ brand, industry }: { brand: string, industry: string }) {
  const [isOpen, setIsOpen] = useState(false);
  const [loading, setLoading] = useState(false);
  const [plan, setPlan] = useState<string | null>(null);
  const [generatedBy, setGeneratedBy] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  async function handleGenerate() {
    setIsOpen(true);
    if (plan) return; // Already generated

    setLoading(true);
    setError(null);
    try {
      const res = await fetch(`/api/rs?brand=${encodeURIComponent(brand)}&industry=${encodeURIComponent(industry)}`);
      const data = await res.json();
      
      if (!res.ok) throw new Error(data.error || 'Failed to generate plan');
      
      setPlan(data.plan);
      setGeneratedBy(data.generatedBy);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Unknown error');
    } finally {
      setLoading(false);
    }
  }

  return (
    <>
      <button 
        onClick={handleGenerate}
        className="mt-6 px-6 py-2.5 bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-500 hover:to-pink-500 text-white text-sm font-bold rounded-xl shadow-lg shadow-purple-500/20 hover:shadow-purple-500/40 transition-all active:scale-95 flex items-center gap-2 w-max"
      >
        <span>⚡</span> rAsh Engine
      </button>

      {isOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm">
          <div className="bg-[#0a0a0f] border border-white/10 rounded-3xl w-full max-w-2xl max-h-[85vh] flex flex-col shadow-2xl overflow-hidden animate-in fade-in zoom-in-95 duration-200">
            
            <div className="px-6 py-4 border-b border-white/10 flex justify-between items-center bg-white/[0.02]">
              <div>
                <h3 className="text-lg font-bold text-white flex items-center gap-2">
                  <span className="text-purple-400">⚡</span> rAsh Engine Action Plan
                </h3>
                <p className="text-xs text-gray-400">LLMO Strategy for {brand}</p>
              </div>
              <button onClick={() => setIsOpen(false)} className="text-gray-400 hover:text-white p-2">
                ✕
              </button>
            </div>

            <div className="p-6 overflow-y-auto flex-1">
              {loading && (
                <div className="flex flex-col items-center justify-center py-12">
                  <div className="w-10 h-10 border-[3px] border-purple-500/30 border-t-purple-500 rounded-full animate-spin mb-4" />
                  <p className="text-purple-400 text-sm font-medium animate-pulse">Analyzing vulnerabilities...</p>
                </div>
              )}

              {error && (
                <div className="bg-red-500/10 border border-red-500/20 text-red-400 p-4 rounded-xl text-sm">
                  ⚠️ {error}
                </div>
              )}

              {plan && (
                <div className="prose prose-sm prose-invert prose-purple max-w-none prose-headings:font-bold prose-h3:text-lg prose-p:text-gray-300">
                  <ReactMarkdown remarkPlugins={[remarkGfm]}>
                    {plan}
                  </ReactMarkdown>
                  
                  {generatedBy && (
                    <div className="mt-8 pt-4 border-t border-white/10 text-[10px] text-gray-500 font-mono text-right">
                      Generated by {generatedBy}
                    </div>
                  )}
                </div>
              )}
            </div>
            
          </div>
        </div>
      )}
    </>
  );
}
