"use client";

import { useState } from "react";
import BrandInput from "@/components/BrandInput";
import LLMOScore from "@/components/LLMOScore";
import AIResponse from "@/components/AIResponse";
import ModelComparison from "@/components/ModelComparison";
import CompetitorComparison from "@/components/CompetitorComparison";
import { SkeletonResults } from "@/components/LoadingSkeleton";
import { useToast } from "@/components/Toast";
import { AnimatedCard, AnimatedSection } from "@/components/AnimatedCard";

export interface BrandCheckResult {
    brand: string;
    category: string;
    score: number;
    responses: {
        model: string;
        modelType: "free" | "pro";
        text: string;
        sentiment: "positive" | "neutral" | "negative";
        mentionsCount: number;
    }[];
    breakdown: {
        recommendation: number;
        sentiment: number;
        prominence: number;
        accuracy: number;
    };
    tips: string[];
    meta?: {
        responseTime: number;
        modelsQueried: number;
        timestamp: string;
    };
}

export default function Home() {
    const [result, setResult] = useState<BrandCheckResult | null>(null);
    const [loading, setLoading] = useState(false);
    const [competitor, setCompetitor] = useState<BrandCheckResult | null>(null);
    const [competitorLoading, setCompetitorLoading] = useState(false);
    const [showAIResponsesModal, setShowAIResponsesModal] = useState(false);
    const { addToast } = useToast();

    const handleBrandCheck = async (brand: string, category: string = "general") => {
        setLoading(true);
        setResult(null);
        setCompetitor(null);

        try {
            const response = await fetch("/api/check-brand", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ brand, category }),
            });

            const data = await response.json();

            if (!response.ok) {
                throw new Error(data.error || "Failed to analyze brand");
            }

            setResult(data);
            addToast(`Analysis complete for ${brand}!`, "success");
        } catch (error) {
            console.error("Error checking brand:", error);
            addToast(
                error instanceof Error ? error.message : "Failed to analyze brand. Please try again.",
                "error"
            );
        } finally {
            setLoading(false);
        }
    };

    const handleCompetitorCheck = async (competitorBrand: string) => {
        if (!result) return;

        if (competitorBrand.trim().toLowerCase() === result.brand.trim().toLowerCase()) {
            addToast("Cannot compare a brand with itself!", "error");
            return;
        }

        setCompetitorLoading(true);

        try {
            const response = await fetch("/api/check-brand", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    brand: competitorBrand,
                    category: result.category
                }),
            });

            const data = await response.json();

            if (!response.ok) {
                throw new Error(data.error || "Failed to analyze competitor");
            }

            setCompetitor(data);
            addToast(`Competitor analysis complete!`, "success");
        } catch (error) {
            console.error("Error checking competitor:", error);
            addToast(
                error instanceof Error ? error.message : "Failed to analyze competitor. Please try again.",
                "error"
            );
        } finally {
            setCompetitorLoading(false);
        }
    };

    const handleCopyResults = async () => {
        if (!result) return;

        const summary = `
rAsh Score Report for ${result.brand}
=========================================
rAsh Score: ${result.score}/100

Breakdown:
- Recommendation: ${result.breakdown.recommendation}/40
- Sentiment: ${result.breakdown.sentiment}/30
- Prominence: ${result.breakdown.prominence}/20
- Accuracy: ${result.breakdown.accuracy}/10

Tips:
${result.tips.map((tip, i) => `${i + 1}. ${tip}`).join("\n")}

Generated by rAsh Score (https://brandscore.kprsnt.in)
        `.trim();

        try {
            await navigator.clipboard.writeText(summary);
            addToast("Results copied to clipboard!", "success");
        } catch {
            addToast("Failed to copy results", "error");
        }
    };

    return (
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
            {/* Hero Section */}
            <section className="text-center mb-10 sm:mb-16 mt-4 sm:mt-8">
                <h1 className="text-2xl sm:text-4xl md:text-5xl font-bold mb-3 sm:mb-4 px-2 leading-snug">
                    Check Your Brand&apos;s <span className="gradient-text">AI Visibility</span>
                </h1>
                <p className="text-sm sm:text-lg md:text-xl text-gray-400 max-w-2xl mx-auto mb-6 sm:mb-8 px-4">
                    See what AI models say about your brand. Get your rAsh Score and discover
                    how to improve your visibility in AI recommendations.
                </p>

                {/* Brand Input */}
                <BrandInput onSubmit={handleBrandCheck} loading={loading} />
            </section>

            {/* Loading State with Skeleton */}
            {loading && <SkeletonResults />}

            {/* Results Section */}
            {result && !loading && (
                <div className="space-y-8">
                    {/* Copy Button */}
                    <div className="flex justify-end">
                        <button
                            onClick={handleCopyResults}
                            className="btn-secondary flex items-center gap-2"
                            aria-label="Copy results to clipboard"
                        >
                            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                            </svg>
                            Copy Results
                        </button>
                    </div>

                    {/* Score and Summary */}
                    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                        <AnimatedCard delay={0.1}>
                            <LLMOScore score={result.score} breakdown={result.breakdown} />
                        </AnimatedCard>

                        <AnimatedCard delay={0.2} className="lg:col-span-2 card p-6">
                            <h3 className="text-lg font-semibold mb-4">
                                📊 AI Analysis for <span className="text-primary-400">{result.brand}</span>
                            </h3>
                            <div className="space-y-4">
                                {result.tips.map((tip, index) => (
                                    <div key={index} className="flex items-start gap-3">
                                        <div className="w-6 h-6 rounded-full bg-primary-500/20 flex items-center justify-center flex-shrink-0 mt-0.5">
                                            <span className="text-primary-400 text-sm">💡</span>
                                        </div>
                                        <p className="text-gray-300">{tip}</p>
                                    </div>
                                ))}
                            </div>
                            {result.meta && (
                                <p className="text-xs text-gray-500 mt-4">
                                    Analysis completed in {result.meta.responseTime}ms using {result.meta.modelsQueried} AI models
                                </p>
                            )}
                        </AnimatedCard>
                    </div>

                    {/* Model Comparison */}
                    <AnimatedSection delay={0.3}>
                        <ModelComparison responses={result.responses} brand={result.brand} />
                    </AnimatedSection>

                    {/* View AI Responses Button */}
                    <AnimatedSection delay={0.4}>
                        <button
                            onClick={() => setShowAIResponsesModal(true)}
                            className="w-full px-6 py-3 bg-gray-800 hover:bg-gray-700 border border-gray-700 
                                       rounded-lg font-medium transition-colors flex items-center justify-center gap-2"
                        >
                            <span>🤖</span>
                            <span>View Detailed AI Responses</span>
                            <span className="text-gray-500">({result.responses.length} models)</span>
                        </button>
                    </AnimatedSection>

                    {/* Competitor Comparison */}
                    <AnimatedSection delay={0.6}>
                        <CompetitorComparison
                            brandResult={result}
                            competitorResult={competitor}
                            onCompare={handleCompetitorCheck}
                            loading={competitorLoading}
                        />
                    </AnimatedSection>
                </div>
            )}

            {/* Features Section */}
            {!result && !loading && (
                <section id="features" className="mt-16" aria-labelledby="features-heading">
                    <h2 id="features-heading" className="text-xl sm:text-2xl font-bold text-center mb-6 sm:mb-8">Why rAsh Score?</h2>
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-4 sm:gap-6">
                        <article className="card card-hover p-5 sm:p-6 text-center">
                            <div className="text-3xl sm:text-4xl mb-3 sm:mb-4" aria-hidden="true">🔍</div>
                            <h3 className="font-semibold text-base sm:text-lg mb-2">Multi-Model Analysis</h3>
                            <p className="text-sm sm:text-base text-gray-400">Check what Gemini, Groq (Llama), and DeepSeek models say about your brand</p>
                        </article>
                        <article className="card card-hover p-5 sm:p-6 text-center">
                            <div className="text-3xl sm:text-4xl mb-3 sm:mb-4" aria-hidden="true">📊</div>
                            <h3 className="font-semibold text-base sm:text-lg mb-2">rAsh Score</h3>
                            <p className="text-sm sm:text-base text-gray-400">Get a 0-100 score measuring your brand&apos;s AI visibility and optimization</p>
                        </article>
                        <article className="card card-hover p-5 sm:p-6 text-center">
                            <div className="text-3xl sm:text-4xl mb-3 sm:mb-4" aria-hidden="true">⚔️</div>
                            <h3 className="font-semibold text-base sm:text-lg mb-2">Competitor Analysis</h3>
                            <p className="text-sm sm:text-base text-gray-400">Compare your AI visibility against competitors</p>
                        </article>
                    </div>
                </section>
            )}

            {/* How It Works */}
            {!result && !loading && (
                <section id="how-it-works" className="mt-12 sm:mt-16" aria-labelledby="how-it-works-heading">
                    <h2 id="how-it-works-heading" className="text-xl sm:text-2xl font-bold text-center mb-6 sm:mb-8">How It Works</h2>
                    <div className="flex flex-col md:flex-row gap-4 justify-center px-4">
                        <div className="flex items-center gap-3 sm:gap-4">
                            <div className="w-8 h-8 sm:w-10 sm:h-10 rounded-full bg-primary-500 flex items-center justify-center font-bold text-sm sm:text-base shrink-0" aria-hidden="true">1</div>
                            <span className="text-sm sm:text-base text-gray-300">Enter your brand name</span>
                        </div>
                        <div className="hidden md:block text-gray-600" aria-hidden="true">→</div>
                        <div className="flex items-center gap-3 sm:gap-4">
                            <div className="w-8 h-8 sm:w-10 sm:h-10 rounded-full bg-primary-500 flex items-center justify-center font-bold text-sm sm:text-base shrink-0" aria-hidden="true">2</div>
                            <span className="text-sm sm:text-base text-gray-300">We query multiple AI models</span>
                        </div>
                        <div className="hidden md:block text-gray-600" aria-hidden="true">→</div>
                        <div className="flex items-center gap-3 sm:gap-4">
                            <div className="w-8 h-8 sm:w-10 sm:h-10 rounded-full bg-primary-500 flex items-center justify-center font-bold text-sm sm:text-base shrink-0" aria-hidden="true">3</div>
                            <span className="text-sm sm:text-base text-gray-300">Get your rAsh Score & insights</span>
                        </div>
                    </div>
                </section>
            )}

            {/* FAQ Section */}
            {!result && !loading && (
                <section id="faq" className="mt-16 sm:mt-20 max-w-4xl mx-auto" aria-labelledby="faq-heading">
                    <h2 id="faq-heading" className="text-xl sm:text-2xl font-bold text-center mb-6 sm:mb-8">Frequently Asked Questions</h2>
                    <div className="space-y-4">
                        <div className="card p-5 sm:p-6 border-l-4 border-l-primary-500">
                            <h3 className="text-base sm:text-lg font-semibold text-white mb-2">Why are we doing this?</h3>
                            <p className="text-gray-400 text-xs sm:text-sm leading-relaxed">
                                AI models like ChatGPT, Gemini, and Claude are rapidly becoming the primary way consumers and businesses search for information. Traditional SEO focuses on Google search results, but <strong>LLM Optimization (LLMO)</strong> is about ensuring your brand is prominently and positively recommended by AI. We built rAsh Score to help you measure and improve your visibility in this new AI-first world.
                            </p>
                        </div>
                        <div className="card p-5 sm:p-6 border-l-4 border-l-purple-500">
                            <h3 className="text-base sm:text-lg font-semibold text-white mb-2">How is the rAsh Score calculated?</h3>
                            <p className="text-gray-400 text-xs sm:text-sm leading-relaxed">
                                The score is out of 100 and is broken down into four key metrics: <strong>Recommendation (40 points)</strong>, <strong>Sentiment (30 points)</strong>, <strong>Prominence (20 points)</strong>, and <strong>Accuracy (10 points)</strong>. We query multiple state-of-the-art models (like Gemini and Llama) and aggregate their responses to create a unified visibility metric.
                            </p>
                        </div>
                        <div className="card p-5 sm:p-6 border-l-4 border-l-pink-500">
                            <h3 className="text-base sm:text-lg font-semibold text-white mb-2">Why might my score vary?</h3>
                            <p className="text-gray-400 text-xs sm:text-sm leading-relaxed">
                                AI models are non-deterministic, meaning they can generate slightly different responses each time they are asked the same question. Additionally, comparing your brand head-to-head against a competitor provides the AI with a different context than a single-brand analysis, which can result in score variations. We use standardized prompting across all our endpoints to minimize this variance as much as possible.
                            </p>
                        </div>
                    </div>
                </section>
            )}

            {/* AI Responses Slide-out Panel */}
            {showAIResponsesModal && result && (
                <div className="fixed inset-0 z-50 flex justify-end">
                    {/* Backdrop */}
                    <div
                        className="absolute inset-0 bg-black/60 backdrop-blur-sm"
                        onClick={() => setShowAIResponsesModal(false)}
                    />

                    {/* Slide-out Panel */}
                    <div className="relative w-full max-w-2xl bg-gray-900 border-l border-gray-700 
                                    shadow-2xl overflow-y-auto animate-slide-in">
                        {/* Header */}
                        <div className="sticky top-0 bg-gray-900 border-b border-gray-700 p-4 flex items-center justify-between">
                            <h2 className="text-xl font-semibold flex items-center gap-2">
                                <span>🤖</span>
                                Detailed AI Responses
                            </h2>
                            <button
                                onClick={() => setShowAIResponsesModal(false)}
                                className="p-2 hover:bg-gray-800 rounded-lg transition-colors"
                                aria-label="Close panel"
                            >
                                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                                </svg>
                            </button>
                        </div>

                        {/* Content */}
                        <div className="p-4 space-y-4">
                            {result.responses.map((response, index) => (
                                <div key={index} className="card p-4">
                                    <AIResponse response={response} />
                                </div>
                            ))}
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
}
