"use client";

import { useState } from "react";
import BrandInput from "@/components/BrandInput";
import LLMOScore from "@/components/LLMOScore";
import AIResponse from "@/components/AIResponse";
import ModelComparison from "@/components/ModelComparison";
import CompetitorComparison from "@/components/CompetitorComparison";
import { SkeletonResults } from "@/components/LoadingSkeleton";
import { useToast } from "@/components/Toast";
import { AnimatedCard, AnimatedSection } from "@/components/AnimatedCard";

export interface BrandCheckResult {
    brand: string;
    score: number;
    responses: {
        model: string;
        modelType: "free" | "pro"; // Kept for compatibility but unused in logic
        text: string;
        sentiment: "positive" | "neutral" | "negative";
        mentionsCount: number;
    }[];
    breakdown: {
        recommendation: number;
        sentiment: number;
        prominence: number;
        accuracy: number;
    };
    tips: string[];
    meta?: {
        responseTime: number;
        modelsQueried: number;
        timestamp: string;
    };
}

export default function Home() {
    const [result, setResult] = useState<BrandCheckResult | null>(null);
    const [loading, setLoading] = useState(false);
    const [competitor, setCompetitor] = useState<BrandCheckResult | null>(null);
    const [competitorLoading, setCompetitorLoading] = useState(false);
    const { addToast } = useToast();

    const handleBrandCheck = async (brand: string, category: string = "general") => {
        setLoading(true);
        setResult(null);
        setCompetitor(null);

        try {
            const response = await fetch("/api/check-brand", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ brand, category }),
            });

            const data = await response.json();

            if (!response.ok) {
                throw new Error(data.error || "Failed to analyze brand");
            }

            setResult(data);
            addToast(`Analysis complete for ${brand}!`, "success");
        } catch (error) {
            console.error("Error checking brand:", error);
            addToast(
                error instanceof Error ? error.message : "Failed to analyze brand. Please try again.",
                "error"
            );
        } finally {
            setLoading(false);
        }
    };

    const handleCompetitorCheck = async (competitorBrand: string) => {
        if (!result) return;
        setCompetitorLoading(true);

        try {
            const response = await fetch("/api/check-brand", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ brand: competitorBrand }),
            });

            const data = await response.json();

            if (!response.ok) {
                throw new Error(data.error || "Failed to analyze competitor");
            }

            setCompetitor(data);
            addToast(`Competitor analysis complete!`, "success");
        } catch (error) {
            console.error("Error checking competitor:", error);
            addToast(
                error instanceof Error ? error.message : "Failed to analyze competitor. Please try again.",
                "error"
            );
        } finally {
            setCompetitorLoading(false);
        }
    };

    const handleCopyResults = async () => {
        if (!result) return;

        const summary = `
Brand Score Report for ${result.brand}
=========================================
Brand Score: ${result.score}/100

Breakdown:
- Recommendation: ${result.breakdown.recommendation}/40
- Sentiment: ${result.breakdown.sentiment}/30
- Prominence: ${result.breakdown.prominence}/20
- Accuracy: ${result.breakdown.accuracy}/10

Tips:
${result.tips.map((tip, i) => `${i + 1}. ${tip}`).join("\n")}

Generated by Brand Score (https://brandscore.kprsnt.in)
        `.trim();

        try {
            await navigator.clipboard.writeText(summary);
            addToast("Results copied to clipboard!", "success");
        } catch {
            addToast("Failed to copy results", "error");
        }
    };

    return (
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
            {/* Hero Section */}
            <section className="text-center mb-16">
                <h1 className="text-4xl sm:text-5xl font-bold mb-4">
                    Check Your Brand&apos;s <span className="gradient-text">AI Visibility</span>
                </h1>
                <p className="text-xl text-gray-400 max-w-2xl mx-auto mb-8">
                    See what AI models say about your brand. Get your Brand Score and discover
                    how to improve your visibility in AI recommendations.
                </p>

                {/* Brand Input */}
                <BrandInput onSubmit={handleBrandCheck} loading={loading} />
            </section>

            {/* Loading State with Skeleton */}
            {loading && <SkeletonResults />}

            {/* Results Section */}
            {result && !loading && (
                <div className="space-y-8">
                    {/* Copy Button */}
                    <div className="flex justify-end">
                        <button
                            onClick={handleCopyResults}
                            className="btn-secondary flex items-center gap-2"
                            aria-label="Copy results to clipboard"
                        >
                            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                            </svg>
                            Copy Results
                        </button>
                    </div>

                    {/* Score and Summary */}
                    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                        <AnimatedCard delay={0.1}>
                            <LLMOScore score={result.score} breakdown={result.breakdown} />
                        </AnimatedCard>

                        <AnimatedCard delay={0.2} className="lg:col-span-2 card p-6">
                            <h3 className="text-lg font-semibold mb-4">
                                📊 AI Analysis for <span className="text-primary-400">{result.brand}</span>
                            </h3>
                            <div className="space-y-4">
                                {result.tips.map((tip, index) => (
                                    <div key={index} className="flex items-start gap-3">
                                        <div className="w-6 h-6 rounded-full bg-primary-500/20 flex items-center justify-center flex-shrink-0 mt-0.5">
                                            <span className="text-primary-400 text-sm">💡</span>
                                        </div>
                                        <p className="text-gray-300">{tip}</p>
                                    </div>
                                ))}
                            </div>
                            {result.meta && (
                                <p className="text-xs text-gray-500 mt-4">
                                    Analysis completed in {result.meta.responseTime}ms using {result.meta.modelsQueried} AI models
                                </p>
                            )}
                        </AnimatedCard>
                    </div>

                    {/* Model Comparison - 3 Models */}
                    <AnimatedSection delay={0.3}>
                        <ModelComparison responses={result.responses} brand={result.brand} />
                    </AnimatedSection>

                    {/* Individual AI Responses */}
                    <AnimatedSection delay={0.4} className="space-y-4">
                        <h3 className="text-xl font-semibold">🤖 detailed AI Responses</h3>
                        <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
                            {result.responses.map((response, index) => (
                                <AnimatedCard key={index} delay={0.5 + index * 0.1}>
                                    <AIResponse response={response} />
                                </AnimatedCard>
                            ))}
                        </div>
                    </AnimatedSection>

                    {/* Competitor Comparison */}
                    <AnimatedSection delay={0.6}>
                        <CompetitorComparison
                            brandResult={result}
                            competitorResult={competitor}
                            onCompare={handleCompetitorCheck}
                            loading={competitorLoading}
                        />
                    </AnimatedSection>
                </div>
            )}

            {/* Features Section */}
            {!result && !loading && (
                <section id="features" className="mt-16" aria-labelledby="features-heading">
                    <h2 id="features-heading" className="text-2xl font-bold text-center mb-8">Why Brand Score?</h2>
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                        <article className="card card-hover p-6 text-center">
                            <div className="text-4xl mb-4" aria-hidden="true">🔍</div>
                            <h3 className="font-semibold text-lg mb-2">Multi-Model Analysis</h3>
                            <p className="text-gray-400">Check what Gemini, Groq (Llama), and OpenRouter models say about your brand</p>
                        </article>
                        <article className="card card-hover p-6 text-center">
                            <div className="text-4xl mb-4" aria-hidden="true">📊</div>
                            <h3 className="font-semibold text-lg mb-2">Brand Score</h3>
                            <p className="text-gray-400">Get a 0-100 score measuring your brand&apos;s AI visibility and optimization</p>
                        </article>
                        <article className="card card-hover p-6 text-center">
                            <div className="text-4xl mb-4" aria-hidden="true">⚔️</div>
                            <h3 className="font-semibold text-lg mb-2">Competitor Analysis</h3>
                            <p className="text-gray-400">Compare your AI visibility against competitors</p>
                        </article>
                    </div>
                </section>
            )}

            {/* How It Works */}
            {!result && !loading && (
                <section id="how-it-works" className="mt-16" aria-labelledby="how-it-works-heading">
                    <h2 id="how-it-works-heading" className="text-2xl font-bold text-center mb-8">How It Works</h2>
                    <div className="flex flex-col md:flex-row gap-4 justify-center">
                        <div className="flex items-center gap-4">
                            <div className="w-10 h-10 rounded-full bg-primary-500 flex items-center justify-center font-bold" aria-hidden="true">1</div>
                            <span className="text-gray-300">Enter your brand name</span>
                        </div>
                        <div className="hidden md:block text-gray-600" aria-hidden="true">→</div>
                        <div className="flex items-center gap-4">
                            <div className="w-10 h-10 rounded-full bg-primary-500 flex items-center justify-center font-bold" aria-hidden="true">2</div>
                            <span className="text-gray-300">We query multiple AI models</span>
                        </div>
                        <div className="hidden md:block text-gray-600" aria-hidden="true">→</div>
                        <div className="flex items-center gap-4">
                            <div className="w-10 h-10 rounded-full bg-primary-500 flex items-center justify-center font-bold" aria-hidden="true">3</div>
                            <span className="text-gray-300">Get your Brand Score & insights</span>
                        </div>
                    </div>
                </section>
            )}
        </div>
    );
}
